### ISSUE TITLE
Some way to run multiple tasks at once

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_task#15]
`lucky db.create,db.migrate,db.create_required_seeds`

And/or with a lucky_cli.yaml file for defining aliases?

```yaml
aliases:
  db.setup:
    - db.create
    - db.migrate
    - db.create_required_seeds
```
